name = "menulinx-trade"
compatibility_date = "2024-09-23"
pages_build_output_dir = "./dist"

[[kv_namespaces]]
binding = "MENULINX_KV"
id = "eb044b3a45ef408bbf1901b198bd0c74"

[[kv_namespaces]]
binding = "MENULINX_SESSIONS"
id = "ca14eccec97349a189d4ba03e98d9bbe"