name = "menulinx-trade"
compatibility_date = "2024-09-23"
pages_build_output_dir = "./dist"

[[kv_namespaces]]
binding = "MENULINX_KV"
id = "377127e0ae9c4e42bb6e5a6ec62665dc"

[[kv_namespaces]]
binding = "MENULINX_SESSIONS"
id = "47e11789c3734944812256cb375ba6c0"